Cp 45 implement stack router for login and registration screen tab screen
AaryTrivedi/capstone-project pull request #17
Opened 2022-01-29 18:02 UTC by rutikpatel

2022-01-29 18:41 UTC, AaryTrivedi commented on frontend/components/Signup.js
> +              SecureStore.setItemAsync('token',data.data.token).then(
use await here like await SecureStore.setItemAsync

2022-01-29 18:41 UTC, AaryTrivedi commented on frontend/components/Signup.js
> +                this.props.navigation.navigate('DashBoard',{screen:'Profile'})
call navigate after setItemAsync. So it will navigate after token is stored

2022-01-29 18:42 UTC, AaryTrivedi commented on frontend/components/Token.js
> +export default async function Token(key='token') {
change name to setToken.
Take the parameter token here like
setToken(token)
The token parameter should be the value returned from the api

2022-01-29 18:43 UTC, AaryTrivedi commented on frontend/components/Token.js
> +    let result = await SecureStore.getItemAsync(key);
instead of key, pass 'token'

2022-01-29 18:43 UTC, AaryTrivedi commented on frontend/components/login.js
> +async function save(key,value){
put this with the getToken helper function

2022-01-29 18:45 UTC, AaryTrivedi requested changes
Please do the required changes

2022-01-29 19:11 UTC, rutikpatel commented
Requested changes done

2022-01-31 22:12 UTC, AaryTrivedi approved these changes
LGTM!

2022-01-31 22:12 UTC, merged